import React, { useState, useEffect, useCallback } from 'react'
import { Heart, Activity, Stethoscope, ChevronLeft, ChevronRight, Loader2, ArrowRight, ShieldCheck, Mail, Phone, MapPin, BookOpen, Menu, X } from 'lucide-react'
import EcgTrace from './components/EcgTrace.jsx'
import LeadRail from './components/LeadRail.jsx'
import { NumberField, OptionPicker } from './components/Fields.jsx'
import ResultPanel from './components/ResultPanel.jsx'
import ModelInfoPanel from './components/ModelInfoPanel.jsx'

const STEPS = [{ lead: 'Lead I', label: 'Personal' }, { lead: 'Lead II', label: 'Vitals' }, { lead: 'Lead III', label: 'Labs' }, { lead: 'Lead V', label: 'Lifestyle' }]
const initialForm = { age_years: 45, gender: 2, height: 170, weight: 75, ap_hi: 120, ap_lo: 80, cholesterol: 1, gluc: 1, smoke: 0, alco: 0, active: 1 }
const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || '').replace(/\\/$/, '')

export default function App() {
  const [page, setPage] = useState('home'); const [menuOpen, setMenuOpen] = useState(false)
  const go = (next) => { setPage(next); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  return <div className="ecg-paper min-h-screen"><Navigation page={page} go={go} open={menuOpen} setOpen={setMenuOpen} /><main>{page === 'home' && <HomePage go={go} />}{page === 'about' && <AboutPage />}{page === 'assessment' && <AssessmentPage />}{page === 'contact' && <ContactPage />}</main><footer className="border-t border-line/70 bg-white/80 px-4 py-7 text-center text-xs text-inkmute"><span className="font-mono font-semibold text-ink">VITALIS</span> · Academic project · Not a substitute for professional medical advice</footer></div>
}

function Navigation({ page, go, open, setOpen }) {
  const links = [['home', 'Home'], ['about', 'About'], ['assessment', 'Risk assessment'], ['contact', 'Contact']]
  return <header className="sticky top-0 z-20 border-b border-line/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><button onClick={() => go('home')} className="flex items-center gap-2.5 text-left" aria-label="Vitalis home"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue text-white"><Heart size={18} fill="currentColor" /></span><span><span className="block font-mono text-[15px] font-semibold leading-none text-ink">VITALIS</span><span className="block pt-1 text-[10px] leading-none text-inkmute">cardiovascular health</span></span></button><nav className="hidden items-center gap-1 md:flex">{links.map(([id, label]) => <NavLink key={id} active={page === id} onClick={() => go(id)}>{label}</NavLink>)}</nav><button className="rounded-lg p-2 text-ink md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={20} /> : <Menu size={20} />}</button></div>{open && <nav className="border-t border-line bg-white px-4 py-3 md:hidden">{links.map(([id, label]) => <button key={id} onClick={() => go(id)} className={`block w-full rounded-lg px-3 py-2.5 text-left text-sm font-medium ${page === id ? 'bg-blue-soft text-blue' : 'text-inkmute'}`}>{label}</button>)}</nav>}</header>
}
function NavLink({ active, onClick, children }) { return <button onClick={onClick} className={`rounded-lg px-3 py-2 text-sm font-medium transition-colors ${active ? 'bg-blue-soft text-blue' : 'text-inkmute hover:bg-slate-100 hover:text-ink'}`}>{children}</button> }

function HomePage({ go }) { return <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-20"><section className="grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="fade-up"><p className="mb-4 flex items-center gap-2 font-mono text-xs font-semibold uppercase tracking-[.18em] text-blue"><Activity size={14} /> Understand your heart health</p><h1 className="max-w-2xl text-4xl font-semibold leading-tight text-ink sm:text-5xl">A clearer view of your cardiovascular risk.</h1><p className="mt-5 max-w-xl text-base leading-7 text-inkmute">Vitalis helps turn everyday health information into an easy-to-understand cardiovascular risk estimate—so you can start a more informed conversation with a healthcare professional.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => go('assessment')} className="flex items-center gap-2 rounded-lg bg-blue px-5 py-3 text-sm font-semibold text-white shadow-sm transition-transform hover:scale-[1.02]"><Heart size={16} /> Start assessment <ArrowRight size={16} /></button><button onClick={() => go('about')} className="rounded-lg border border-line bg-white px-5 py-3 text-sm font-semibold text-ink hover:border-blue">Learn about heart health</button></div></div><div className="rounded-card border border-line bg-panel p-5 shadow-sm fade-up"><div className="flex items-center justify-between"><span className="font-mono text-xs font-semibold text-blue">LIVE CARDIAC SIGNAL</span><span className="flex items-center gap-1.5 text-xs text-green"><i className="pulse-dot h-2 w-2 rounded-full bg-green" /> MONITORING</span></div><EcgTrace beats={6} amplitude={1.05} color="#2456A6" height={145} /><div className="grid grid-cols-3 border-t border-line pt-4 text-center"><Stat value="4" label="health areas" /><Stat value="~62K" label="training records" /><Stat value="< 3 min" label="to complete" /></div></div></section><section className="mt-16 grid gap-4 md:grid-cols-3"><Feature icon={<ShieldCheck />} title="Private by design" text="Your assessment is used only to generate your risk estimate." /><Feature icon={<BookOpen />} title="Plain-language guidance" text="Explore the factors that can influence cardiovascular health." /><Feature icon={<Activity />} title="Data-informed estimate" text="Built around a logistic-regression model trained on patient data." /></section></div> }
function Stat({ value, label }) { return <div><div className="font-mono text-lg font-semibold text-ink">{value}</div><div className="mt-1 text-[11px] text-inkmute">{label}</div></div> }
function Feature({ icon, title, text }) { return <article className="rounded-card border border-line bg-white/80 p-5"><span className="mb-4 block text-blue">{React.cloneElement(icon, { size: 21 })}</span><h2 className="font-semibold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-inkmute">{text}</p></article> }

function AboutPage() { const [metrics, setMetrics] = useState(null); useEffect(() => { fetch(`${API_BASE_URL}/api/model-info`).then((r) => r.json()).then(setMetrics).catch(() => {}) }, []); const factors = [['Blood pressure', 'High blood pressure can place extra strain on the heart and blood vessels.'], ['Cholesterol & glucose', 'These laboratory measures can be important markers to discuss with your clinician.'], ['Movement & habits', 'Physical activity, tobacco use, and alcohol intake all help shape overall risk.'], ['Age & body measures', 'Age, height, and weight provide context for the rest of the picture.']]; return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="font-mono text-xs font-semibold uppercase tracking-[.18em] text-blue">About cardiovascular disease</p><h1 className="mt-3 max-w-3xl text-3xl font-semibold text-ink sm:text-4xl">Heart health is shaped by many connected factors.</h1><p className="mt-4 max-w-3xl text-base leading-7 text-inkmute">Cardiovascular disease refers to conditions affecting the heart and blood vessels. Risk is personal and cannot be diagnosed by an online tool—but understanding the signals can support prevention and timely medical care.</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{factors.map(([title, text], i) => <article key={title} className="rounded-card border border-line bg-white/80 p-5"><span className="font-mono text-sm font-semibold text-blue">0{i + 1}</span><h2 className="mt-4 font-semibold text-ink">{title}</h2><p className="mt-2 text-sm leading-6 text-inkmute">{text}</p></article>)}</div><section className="mt-10 rounded-card border border-line bg-panel p-6 md:p-8"><h2 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-inkmute"><Stethoscope size={16} /> About the Vitalis model</h2><div className="mt-5"><ModelInfoPanel metrics={metrics} /></div></section></div> }

function AssessmentPage() { const [step, setStep] = useState(0), [form, setForm] = useState(initialForm), [result, setResult] = useState(null), [loading, setLoading] = useState(false), [error, setError] = useState(null); const set = (key) => (value) => setForm((f) => ({ ...f, [key]: value })); const submit = useCallback(async () => { setLoading(true); setError(null); try { const res = await fetch(`${API_BASE_URL}/api/predict`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) { const body = await res.json().catch(() => ({})); throw new Error(body.detail || 'Prediction failed. Check that the API is deployed and reachable.') }; setResult(await res.json()) } catch (e) { setError(e.message) } finally { setLoading(false) } }, [form]); return <div className="mx-auto max-w-4xl px-4 py-12 sm:px-6"><div className="mb-8"><p className="font-mono text-xs font-semibold uppercase tracking-[.18em] text-blue">Risk assessment</p><h1 className="mt-3 text-3xl font-semibold text-ink">Four short leads. One clearer picture.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-inkmute">Provide general health information for an educational cardiovascular-risk estimate.</p></div>{result ? <ResultPanel result={result} onRestart={() => { setResult(null); setStep(0) }} /> : <section><LeadRail steps={STEPS} activeIndex={step} /><div className="mt-5 rounded-card border border-line bg-panel p-6 fade-up md:p-8" key={step}><AssessmentFields step={step} form={form} set={set} />{error && <div className="mt-4 rounded-lg border border-red/30 bg-red-soft px-3 py-2 text-sm text-red">{error}</div>}<div className="mt-7 flex items-center justify-between"><button onClick={() => setStep((s) => Math.max(s - 1, 0))} disabled={step === 0} className="flex items-center gap-1 rounded-lg px-3 py-2 text-sm font-medium text-inkmute hover:text-ink disabled:opacity-0"><ChevronLeft size={16} /> Back</button>{step < 3 ? <button onClick={() => setStep((s) => s + 1)} className="flex items-center gap-1.5 rounded-lg bg-blue px-4 py-2.5 text-sm font-semibold text-white">Next lead <ChevronRight size={16} /></button> : <button onClick={submit} disabled={loading} className="flex items-center gap-2 rounded-lg bg-red px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-70">{loading ? <Loader2 size={16} className="animate-spin" /> : <Heart size={16} />}{loading ? 'Reading vitals…' : 'Run risk analysis'}</button>}</div></div></section>}</div> }
function AssessmentFields({ step, form, set }) { return <div className="grid gap-5 sm:grid-cols-2">{step === 0 && <><NumberField label="Age" unit="years" min={1} max={120} value={form.age_years} onChange={set('age_years')} /><OptionPicker label="Gender" value={form.gender} onChange={set('gender')} options={[{ value: 1, label: 'Female' }, { value: 2, label: 'Male' }]} /><NumberField label="Height" unit="cm" min={100} max={220} value={form.height} onChange={set('height')} /><NumberField label="Weight" unit="kg" min={20} max={250} step={0.5} value={form.weight} onChange={set('weight')} /></>}{step === 1 && <><NumberField label="Systolic BP (ap_hi)" unit="mmHg" min={60} max={260} value={form.ap_hi} onChange={set('ap_hi')} hint="The top number on a blood pressure reading" /><NumberField label="Diastolic BP (ap_lo)" unit="mmHg" min={30} max={200} value={form.ap_lo} onChange={set('ap_lo')} hint="The bottom number on a blood pressure reading" /></>}{step === 2 && <><OptionPicker label="Cholesterol" value={form.cholesterol} onChange={set('cholesterol')} options={[{ value: 1, label: 'Normal' }, { value: 2, label: 'Above normal' }, { value: 3, label: 'Well above' }]} /><OptionPicker label="Glucose" value={form.gluc} onChange={set('gluc')} options={[{ value: 1, label: 'Normal' }, { value: 2, label: 'Above normal' }, { value: 3, label: 'Well above' }]} /></>}{step === 3 && <><OptionPicker label="Smoker" value={form.smoke} onChange={set('smoke')} options={[{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }]} /><OptionPicker label="Alcohol intake" value={form.alco} onChange={set('alco')} options={[{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }]} /><OptionPicker label="Physically active" value={form.active} onChange={set('active')} options={[{ value: 0, label: 'No' }, { value: 1, label: 'Yes' }]} /></>}</div> }

function ContactPage() { return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><p className="font-mono text-xs font-semibold uppercase tracking-[.18em] text-blue">Contact us</p><h1 className="mt-3 text-3xl font-semibold text-ink sm:text-4xl">Questions about Vitalis?</h1><p className="mt-4 max-w-2xl leading-7 text-inkmute">Use this page as the contact point for your project. Replace the sample details below with your team’s real information before publishing.</p><div className="mt-10 grid gap-5 md:grid-cols-2"><section className="rounded-card border border-line bg-white/85 p-6"><h2 className="font-semibold text-ink">Project contact</h2><div className="mt-6 space-y-5 text-sm text-inkmute"><ContactItem icon={<Mail />} label="Email" value="hello@vitalis-health.example" /><ContactItem icon={<Phone />} label="Phone" value="+91 00000 00000" /><ContactItem icon={<MapPin />} label="Location" value="Your university / organization" /></div></section><form className="rounded-card border border-line bg-panel p-6" onSubmit={(e) => e.preventDefault()}><h2 className="font-semibold text-ink">Send a message</h2><p className="mt-1 text-xs text-inkmute">Demo form — connect it to your backend or email service.</p><label className="mt-5 block text-sm font-medium text-ink">Name<input className="mt-1.5 w-full rounded-lg border border-line bg-white px-3 py-2.5 outline-none focus:border-blue" placeholder="Your name" /></label><label className="mt-4 block text-sm font-medium text-ink">Email<input type="email" className="mt-1.5 w-full rounded-lg border border-line bg-white px-3 py-2.5 outline-none focus:border-blue" placeholder="you@example.com" /></label><label className="mt-4 block text-sm font-medium text-ink">Message<textarea rows="3" className="mt-1.5 w-full resize-none rounded-lg border border-line bg-white px-3 py-2.5 outline-none focus:border-blue" placeholder="How can we help?" /></label><button className="mt-5 rounded-lg bg-blue px-4 py-2.5 text-sm font-semibold text-white">Send message</button></form></div></div> }
function ContactItem({ icon, label, value }) { return <div className="flex gap-3"><span className="text-blue">{React.cloneElement(icon, { size: 18 })}</span><div><div className="text-xs font-semibold uppercase tracking-wide text-inkmute">{label}</div><div className="mt-0.5 text-ink">{value}</div></div></div> }
